import 'package:firebase_database/firebase_database.dart';

class FirebaseHelperMotherboards {
  final DatabaseReference _motherboardsRef = FirebaseDatabase.instance.ref('motherboards'); // 'motherboards' node

  // Function to add motherboard data to Firebase manually
  Future<void> addMotherboardDataManually() async {
    // Sample motherboard data with image URLs
    final motherboardData = [
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/ca980d24c4cc99996e802092f9590bcf.1600.jpg',
        'name': 'MSI B650 GAMING PLUS WIFI',
        'socket': 'AM5',
        'formFactor': 'ATX',
        'maxMemory': '192 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 41,997',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/cbc52effd345bd5e9d66b5f7d198f8b4.1600.jpg',
        'name': 'MSI B550 GAMING GEN3',
        'socket': 'AM4',
        'formFactor': 'ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 27,997',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/a3020fc8322a2821927ed01af1155620.1600.jpg',
        'name': 'MSI PRO B650-S WIFI',
        'socket': 'AM5',
        'formFactor': 'ATX',
        'maxMemory': '192 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 41,997',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/dc9235e0d8052745493eb900bb9df6f6.1600.jpg',
        'name': 'MSI MAG B650 TOMAHAWK WIFI',
        'socket': 'AM5',
        'formFactor': 'ATX',
        'maxMemory': '256 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 50,397',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51BdjazabVL.jpg',
        'name': 'Gigabyte B650 EAGLE AX',
        'socket': 'AM5',
        'formFactor': 'ATX',
        'maxMemory': '192 GB',
        'slots': 4,
        'color': 'Gray / Black',
        'price': 'PKR 44,797',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/d7893755609db1feb833c99ad9d243bf.1600.jpg',
        'name': 'ASRock B650M Pro RS WiFi',
        'socket': 'AM5',
        'formFactor': 'Micro ATX',
        'maxMemory': '256 GB',
        'slots': 4,
        'color': 'Black / Silver',
        'price': 'N/A',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/ff4b4e2c7f72b014f39f1864b19e7250.1600.jpg',
        'name': 'Asus PRIME B550M-A WIFI II',
        'socket': 'AM4',
        'formFactor': 'Micro ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'Blue / Silver',
        'price': 'PKR 27,997',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/f22d681ccfd01238e756443a474f400b.1600.jpg',
        'name': 'MSI B760 GAMING PLUS WIFI',
        'socket': 'LGA1700',
        'formFactor': 'ATX',
        'maxMemory': '192 GB',
        'slots': 4,
        'color': 'Black / Silver',
        'price': 'PKR 41,997',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/1e1c3a84fdb8ea01eec98abd4c40d5d8.1600.jpg',
        'name': 'Gigabyte X870E AORUS ELITE WIFI7',
        'socket': 'AM5',
        'formFactor': 'ATX',
        'maxMemory': '256 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 89,597',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/127cc163cf3e552499471f1908f99cfe.1600.jpg',
        'name': 'Asus ROG STRIX B650-A GAMING WIFI',
        'socket': 'AM5',
        'formFactor': 'ATX',
        'maxMemory': '192 GB',
        'slots': 4,
        'color': 'Black / Silver',
        'price': 'PKR 53,197',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/41vgwexGr2L.jpg',
        'name': 'Asus TUF GAMING B650M-PLUS WIFI II',
        'socket': 'AM5',
        'formFactor': 'Micro ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'Black / Gray',
        'price': 'PKR 41,997',
      },
      {
        'image': 'https://m.media-amazon.com/images/I/51Hz3u7PR0L.jpg',
        'name': 'Gigabyte B550I AORUS PRO AX',
        'socket': 'AM4',
        'formFactor': 'Mini ITX',
        'maxMemory': '64 GB',
        'slots': 2,
        'color': 'Black',
        'price': 'PKR 55,997',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/8759f89d039f01404d65dcb994629292.1600.jpg',
        'name': 'Asus PRIME Z790-A WIFI II',
        'socket': 'LGA1700',
        'formFactor': 'ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'White / Silver',
        'price': 'PKR 83,997',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/cf20560e7e4a9e474fcb4c88238e4ffd.1600.jpg',
        'name': 'MSI MAG X670E TOMAHAWK WIFI',
        'socket': 'AM5',
        'formFactor': 'ATX',
        'maxMemory': '256 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 81,197',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/40e47e0c22c38ba2269880dd81c305f3.1600.jpg',
        'name': 'ASRock B550 Phantom Gaming-ITX/AX',
        'socket': 'AM4',
        'formFactor': 'Mini ITX',
        'maxMemory': '64 GB',
        'slots': 2,
        'color': 'Black / Silver',
        'price': 'PKR 53,197',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/4776555bd90ed817bdfa00fc78ae3043.1600.jpg',
        'name': 'MSI MEG Z790 ACE',
        'socket': 'LGA1700',
        'formFactor': 'E-ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'Black / Gold',
        'price': 'PKR 195,997',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/308921dd82c7029537edd075cf518569.1600.jpg',
        'name': 'Asus ROG CROSSHAIR X670E HERO',
        'socket': 'AM5',
        'formFactor': 'ATX',
        'maxMemory': '256 GB',
        'slots': 4,
        'color': 'Black / Silver',
        'price': 'PKR 139,997',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/607f7ca77131a0bf7dc6b75617795203.1600.jpg',
        'name': 'MSI MPG B550 GAMING EDGE WIFI',
        'socket': 'AM4',
        'formFactor': 'ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 47,597',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/959c60578b19c2067f96036a19691ac0.1600.jpg',
        'name': 'Gigabyte B650M DS3H',
        'socket': 'AM5',
        'formFactor': 'Micro ATX',
        'maxMemory': '192 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 33,597',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/ff4b4e2c7f72b014f39f1864b19e7250.1600.jpg',
        'name': 'Asus PRIME B650M-A WIFI',
        'socket': 'AM5',
        'formFactor': 'Micro ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'White / Silver',
        'price': 'PKR 36,397',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/55e781311c4d62e83df9ac297a64c01a.1600.jpg',
        'name': 'MSI PRO Z790-A WIFI',
        'socket': 'LGA1700',
        'formFactor': 'ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 58,797',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/2b2897ac0de148a2935c3277573131b3.1600.jpg',
        'name': 'ASRock B450M-HDV R4.0',
        'socket': 'AM4',
        'formFactor': 'Micro ATX',
        'maxMemory': '32 GB',
        'slots': 2,
        'color': 'Black',
        'price': 'PKR 19,597',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/aeb8a7dad48da098b42945e9439076fe.1600.jpg',
        'name': 'Asus TUF GAMING Z790-PLUS WIFI',
        'socket': 'LGA1700',
        'formFactor': 'ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 67,197',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/3d487ee6ea150ca534c123f409cbae68.1600.jpg',
        'name': 'Gigabyte Z690 UD AX DDR4',
        'socket': 'LGA1700',
        'formFactor': 'ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'Black / Silver',
        'price': 'PKR 50,397',
      },
      {
        'image': 'https://cdna.pcpartpicker.com/static/forever/images/product/fac31c8cea999908580b1081eed58c0e.1600.jpg',
        'name': 'MSI MPG X670E CARBON WIFI',
        'socket': 'AM5',
        'formFactor': 'ATX',
        'maxMemory': '128 GB',
        'slots': 4,
        'color': 'Black',
        'price': 'PKR 120,397',
      }
    ];

    try {
      for (var motherboard in motherboardData) {
        await _motherboardsRef.push().set(motherboard);
      }
      print("Motherboard data with images added successfully!");
    } catch (error) {
      print("Error adding motherboard data: $error");
    }
  }
}
