class PcBuildData {
  static const List<Map<String, dynamic>> gamingBuilds = [
    {
      "minBudget": 50000,
      "maxBudget": 70000,
      "build": {
        "Processor": "AMD Ryzen 3 3100",
        "GPU": "NVIDIA GTX 1650",
        "RAM": "16GB DDR4 3200MHz",
        "SSD": "Crucial BX500 240GB SSD",
        "HDD": "Seagate Barracuda 1TB HDD",
        "Motherboard": "ASRock B450M-HDV R4.0",
        "PowerSupply": "Antec VP450P",
        "Case": "Deepcool Matrexx 30",
      },
    },
    {
      "minBudget": 70001,
      "maxBudget": 90000,
      "build": {
        "Processor": "AMD Ryzen 5 3500X",
        "GPU": "NVIDIA GTX 1660 Super",
        "RAM": "16GB DDR4 3200MHz",
        "SSD": "Kingston A2000 500GB NVMe SSD",
        "HDD": "WD Blue 1TB HDD",
        "Motherboard": "MSI B450M Pro-VDH Max",
        "PowerSupply": "Cooler Master MWE 550W",
        "Case": "NZXT H510",
      },
    },
    {
      "minBudget": 90001,
      "maxBudget": 110000,
      "build": {
        "Processor": "Intel Core i5-11400F",
        "GPU": "NVIDIA RTX 2060",
        "RAM": "16GB DDR4 3200MHz",
        "SSD": "Samsung 970 EVO 500GB NVMe SSD",
        "HDD": "Seagate Barracuda 2TB HDD",
        "Motherboard": "ASUS Prime B560M-A",
        "PowerSupply": "Corsair CX650",
        "Case": "Cooler Master MB511 ARGB",
      },
    },
    {
      "minBudget": 110001,
      "maxBudget": 130000,
      "build": {
        "Processor": "AMD Ryzen 5 5600X",
        "GPU": "NVIDIA RTX 3060",
        "RAM": "16GB DDR4 3600MHz",
        "SSD": "Samsung 980 1TB NVMe SSD",
        "HDD": "WD Black 2TB HDD",
        "Motherboard": "MSI B550-A Pro",
        "PowerSupply": "Corsair RM750",
        "Case": "Phanteks P300A Mesh",
      },
    },
    {
      "minBudget": 130001,
      "maxBudget": 150000,
      "build": {
        "Processor": "Intel Core i5-12600K",
        "GPU": "NVIDIA RTX 3060 Ti",
        "RAM": "32GB DDR4 3600MHz",
        "SSD": "Samsung 980 Pro 1TB NVMe SSD",
        "HDD": "Seagate Barracuda 4TB HDD",
        "Motherboard": "ASUS TUF Gaming Z690-Plus",
        "PowerSupply": "Cooler Master MWE 750W",
        "Case": "Corsair 4000D Airflow",
      },
    },
    {
      "minBudget": 150001,
      "maxBudget": 200000,
      "build": {
        "Processor": "AMD Ryzen 7 5800X",
        "GPU": "NVIDIA RTX 3070",
        "RAM": "32GB DDR4 3600MHz",
        "SSD": "Samsung 980 Pro 2TB NVMe SSD",
        "HDD": "WD Black 4TB HDD",
        "Motherboard": "MSI MAG B550 Tomahawk",
        "PowerSupply": "Corsair RM850x",
        "Case": "Fractal Design Meshify C",
      },
    },
    {
      "minBudget": 200001,
      "maxBudget": 250000,
      "build": {
        "Processor": "Intel Core i7-12700K",
        "GPU": "NVIDIA RTX 3080",
        "RAM": "32GB DDR5 4800MHz",
        "SSD": "Samsung 980 Pro 2TB NVMe SSD",
        "HDD": "Seagate IronWolf 6TB HDD",
        "Motherboard": "ASUS ROG Strix Z690-F",
        "PowerSupply": "Seasonic Focus GX-850",
        "Case": "Lian Li Lancool II Mesh",
      },
    },
    {
      "minBudget": 250001,
      "maxBudget": 300000,
      "build": {
        "Processor": "AMD Ryzen 9 5950X",
        "GPU": "NVIDIA RTX 3080 Ti",
        "RAM": "64GB DDR4 3600MHz",
        "SSD": "Samsung 980 Pro 2TB NVMe SSD",
        "HDD": "Seagate IronWolf Pro 8TB HDD",
        "Motherboard": "ASUS ROG Crosshair VIII Dark Hero",
        "PowerSupply": "Corsair AX1000",
        "Case": "Lian Li PC-O11 Dynamic XL",
      },
    },
    {
      "minBudget": 300001,
      "maxBudget": 400000,
      "build": {
        "Processor": "Intel Core i9-13900K",
        "GPU": "NVIDIA RTX 4090",
        "RAM": "64GB DDR5 5200MHz",
        "SSD": "Samsung 990 Pro 2TB NVMe SSD",
        "HDD": "WD Gold 12TB HDD",
        "Motherboard": "MSI MEG Z690 Godlike",
        "PowerSupply": "Corsair HX1200i",
        "Case": "Corsair 7000D Airflow",
      },
    },
    {
      "minBudget": 400001,
      "maxBudget": 500000,
      "build": {
        "Processor": "AMD Threadripper 3970X",
        "GPU": "NVIDIA RTX 4090",
        "RAM": "128GB DDR4 ECC 3200MHz",
        "SSD": "Samsung 990 Pro 4TB NVMe SSD",
        "HDD": "Seagate Exos X16 16TB HDD",
        "Motherboard": "ASUS ROG Zenith II Extreme Alpha",
        "PowerSupply": "Seasonic Prime TX-1600",
        "Case": "Thermaltake Tower 900",
      },
    },
  ];


      static const List<Map<String, dynamic>> officeWorkBuilds = [
        {
          "minBudget": 50000,
          "maxBudget": 70000,
          "build": {
            "Processor": "Intel Core i3-12100",
            "GPU": "Integrated UHD Graphics 730",
            "RAM": "8GB DDR4 3200MHz",
            "SSD": "Crucial BX500 480GB SSD",
            "HDD": "WD Blue 1TB HDD",
            "Motherboard": "Gigabyte B660M DS3H",
            "PowerSupply": "Antec VP450P",
            "Case": "Deepcool Matrexx 30",
          },
        },
        {
          "minBudget": 70001,
          "maxBudget": 90000,
          "build": {
            "Processor": "Intel Core i5-12400",
            "GPU": "Integrated UHD Graphics 750",
           "RAM": "16GB DDR4 3200MHz",
            "SSD": "Samsung 970 EVO Plus 500GB NVMe SSD",
            "HDD": "Seagate Barracuda 2TB HDD",
            "Motherboard": "ASRock B560M Pro4",
            "PowerSupply": "Cooler Master MWE 550W",
            "Case": "NZXT H510",
          },
        },
        {
          "minBudget": 90001,
          "maxBudget": 110000,
          "build": {
            "Processor": "AMD Ryzen 5 5600G",
            "GPU": "Integrated Radeon Vega 7",
            "RAM": "16GB DDR4 3600MHz",
            "SSD": "Samsung 980 1TB NVMe SSD",
            "HDD": "WD Black 2TB HDD",
            "Motherboard": "ASUS Prime B550M-A",
            "PowerSupply": "Corsair CX650",
            "Case": "Fractal Design Focus G",
          },
        },
        {
          "minBudget": 110001,
          "maxBudget": 130000,
          "build": {
            "Processor": "Intel Core i7-12700",
            "GPU": "Integrated UHD Graphics 770",
            "RAM": "32GB DDR5 4800MHz",
            "SSD": "Samsung 980 Pro 1TB NVMe SSD",
            "HDD": "Seagate Barracuda 4TB HDD",
            "Motherboard": "ASUS ROG Strix B660-I",
            "PowerSupply": "Cooler Master MWE 750W",
            "Case": "Be Quiet! Pure Base 500DX",
          },
        },
        {
          "minBudget": 130001,
          "maxBudget": 150000,
          "build": {
            "Processor": "AMD Ryzen 7 5700G",
            "GPU": "Integrated Radeon Vega 8",
            "RAM": "32GB DDR4 3600MHz",
            "SSD": "Samsung 980 Pro 2TB NVMe SSD",
            "HDD": "Seagate Barracuda 4TB HDD",
           " Motherboard": "ASUS Prime B550M-A",
            "PowerSupply": "Corsair RM750",
            "Case": "Lian Li Lancool II",
          },
        },
        {
          "minBudget": 150001,
          "maxBudget": 200000,
          "build": {
            "Processor": "Intel Core i9-12900",
            "GPU": "Integrated UHD Graphics 770",
            "RAM": "64GB DDR5 4800MHz",
            "SSD": "Samsung 980 Pro 2TB NVMe SSD",
            "HDD": "WD Black 4TB HDD",
            "Motherboard": "ASUS ROG Strix Z690-F",
            "PowerSupply": "Corsair RM850",
            "Case": "NZXT H710i",
          },
        },
        {
          "minBudget": 200001,
          "maxBudget": 300000,
          "build": {
            "Processor": "AMD Ryzen 9 5900G",
            "GPU": "Integrated Radeon Vega 11",
            "RAM": "128GB DDR4 3200MHz",
            "SSD": "Samsung 980 Pro 4TB NVMe SSD",
           "HDD": "Seagate IronWolf 6TB HDD",
            "Motherboard": "ASUS ROG Strix B550-F",
            "PowerSupply": "EVGA SuperNOVA 1000W",
            "Case": "Corsair 5000X RGB",
          },
        },
      ];


  static const List<Map<String, dynamic>> graphicDesigningBuilds = [
    {
      "minBudget": 50000,
      "maxBudget": 70000,
      "build": {
        "Processor": "AMD Ryzen 5 3600",
        "GPU": "NVIDIA GTX 1650",
        "RAM": "16GB DDR4 3200MHz",
        "SSD": "Kingston A2000 240GB NVMe SSD",
        "HDD": "WD Blue 1TB HDD",
        "Motherboard": "ASRock B450M Steel Legend",
        "PowerSupply": "Antec VP450P",
        "Case": "Deepcool Matrexx 30",
      },
    },
    {
      "minBudget": 70001,
      "maxBudget": 90000,
      "build": {
        "Processor": "Intel Core i5-10400F",
        "GPU": "NVIDIA GTX 1660 Super",
        "RAM": "16GB DDR4 3200MHz",
        "SSD": "Samsung 970 EVO 500GB NVMe SSD",
        "HDD": "Seagate Barracuda 2TB HDD",
        "Motherboard": "MSI B560M Pro-VDH",
        "PowerSupply": "Cooler Master MWE 550W",
        "Case": "NZXT H510",
      },
    },
    {
      "minBudget": 90001,
      "maxBudget": 110000,
      "build": {
        "Processor": "AMD Ryzen 7 3700X",
        "GPU": "NVIDIA RTX 2060",
        "RAM": "32GB DDR4 3600MHz",
        "SSD": "Samsung 980 Pro 1TB NVMe SSD",
        "HDD": "WD Black 2TB HDD",
        "Motherboard": "MSI B550-A Pro",
        "PowerSupply": "Corsair RM750",
        "Case": "Fractal Design Meshify C",
      },
    },
    {
      "minBudget": 110001,
      "maxBudget": 130000,
      "build": {
        "Processor": "Intel Core i7-12700F",
        "GPU": "NVIDIA RTX 3060",
        "RAM": "32GB DDR5 4800MHz",
        "SSD": "Samsung 980 Pro 1TB NVMe SSD",
        "HDD": "Seagate Barracuda 4TB HDD",
        "Motherboard": "ASUS ROG Strix B660-F",
        "PowerSupply": "Corsair RM850",
        "Case": "Phanteks Eclipse P500A",
      },
    },
    {
      "minBudget": 130001,
      "maxBudget": 150000,
      "build": {
        "Processor": "AMD Ryzen 9 5900X",
        "GPU": "NVIDIA RTX 3070",
        "RAM": "32GB DDR4 3600MHz",
        "SSD": "Samsung 980 Pro 1TB NVMe SSD",
        "HDD": "WD Black 4TB HDD",
        "Motherboard": "MSI MPG B550 Gaming Edge WiFi",
        "PowerSupply": "Corsair RM850x",
        "Case": "Lian Li Lancool II Mesh",
      },
    },
    {
      "minBudget": 150001,
      "maxBudget": 200000,
      "build": {
        "Processor": "Intel Core i9-12900",
        "GPU": "NVIDIA RTX 3080",
        "RAM": "64GB DDR5 5200MHz",
        "SSD": "Samsung 980 Pro 2TB NVMe SSD",
        "HDD": "Seagate IronWolf 6TB HDD",
        "Motherboard": "ASUS ROG Strix Z690-E Gaming",
        "PowerSupply": "Seasonic Focus GX-1000",
        "Case": "Corsair 5000D Airflow",
      },
    },
    {
      "minBudget": 200001,
      "maxBudget": 250000,
      "build": {
        "Processor": "AMD Ryzen 9 5900X",
        "GPU": "NVIDIA RTX 3080 Ti",
        "RAM": "64GB DDR4 3600MHz",
        "SSD": "Samsung 980 Pro 2TB NVMe SSD",
        "HDD": "WD Black 6TB HDD",
        "Motherboard": "MSI MPG X570 Gaming Pro Carbon WiFi",
        "PowerSupply": "Corsair RM1000x",
        "Case": "Fractal Design Define 7",
      },
    },
    {
      "minBudget": 250001,
      "maxBudget": 300000,
      "build": {
        "Processor": "Intel Core i9-12900K",
        "GPU": "NVIDIA RTX 3090",
        "RAM": "64GB DDR5 5200MHz",
        "SSD": "Samsung 980 Pro 4TB NVMe SSD",
        "HDD": "Seagate IronWolf Pro 8TB HDD",
        "Motherboard": "ASUS ROG Strix Z690-F Gaming",
        "PowerSupply": "Seasonic Prime PX-1300",
        "Case": "Phanteks Evolv X",
      },
    },
    {
      "minBudget": 300001,
      "maxBudget": 400000,
      "build": {
        "Processor": "AMD Ryzen 9 7950X",
        "GPU": "NVIDIA RTX 4080",
        "RAM": "128GB DDR5 5600MHz",
        "SSD": "Samsung 990 Pro 4TB NVMe SSD",
        "HDD": "WD Black 10TB HDD",
        "Motherboard": "ASUS ROG Crosshair X670E Hero",
        "PowerSupply": "Corsair HX1500i",
        "Case": "Lian Li PC-O11 Dynamic XL",
      },
    },
  {
      "minBudget": 400001,
      "maxBudget": 500000,
      "build": {
        "Processor": "Intel Core i9-13900K",
        "GPU": "NVIDIA RTX 4090",
        "RAM": "128GB DDR5 6000MHz",
        "SSD": "Samsung 990 Pro 8TB NVMe SSD",
        "HDD": "Seagate Exos X16 16TB HDD",
        "Motherboard": "MSI MEG Z690 Godlike",
        "PowerSupply": "EVGA SuperNOVA 1600 P2",
        "Case": "Corsair 7000D Airflow",
      },
    },
  ]
  ;
}
