class PcBuildData {
  static const List<Map<String, dynamic>> gamingBuilds = [
    {
      "minBudget": 50000,
      "maxBudget": 70000,
      "build": {
        "Processor": "AMD Ryzen 5 3600",
        "GPU": "NVIDIA GTX 1650",
        "RAM": "16GB DDR4",
        "SSD": "Kingston 240GB SSD",
        "HDD": "WD Blue 1TB HDD",
        "Motherboard": "MSI B450 Tomahawk",
        "PowerSupply": "Corsair CX550",
        "Case": "Cooler Master MB511",
      },
    },
    {
      "minBudget": 70001,
      "maxBudget": 90000,
      "build": {
        "Processor": "Intel i5-12400F",
        "GPU": "NVIDIA RTX 3050",
        "RAM": "16GB DDR4",
        "SSD": "Samsung 500GB NVMe SSD",
        "HDD": "WD Blue 1TB HDD",
        "Motherboard": "ASUS TUF B560M-Plus",
        "PowerSupply": "Cooler Master MWE 650W",
        "Case": "NZXT H510",
      },
    },
    {
      "minBudget": 90001,
      "maxBudget": 120000,
      "build": {
        "Processor": "Intel i7-12700",
        "GPU": "NVIDIA RTX 3060 Ti",
        "RAM": "16GB DDR4",
        "SSD": "Samsung 1TB NVMe SSD",
        "HDD": "Seagate 2TB HDD",
        "Motherboard": "ASRock Z690 Phantom Gaming",
        "PowerSupply": "Corsair RM750",
        "Case": "Fractal Design Meshify C",
      },
    },
    {
      "minBudget": 120001,
      "maxBudget": 150000,
      "build": {
        "Processor": "AMD Ryzen 7 5800X",
        "GPU": "NVIDIA RTX 3070",
        "RAM": "32GB DDR4",
        "SSD": "Corsair 1TB NVMe SSD",
        "HDD": "WD Black 2TB HDD",
        "Motherboard": "MSI MAG X570 TOMAHAWK WIFI",
        "PowerSupply": "EVGA SuperNOVA 750 G5",
        "Case": "Corsair 4000D Airflow",
      },
    },
    {
      "minBudget": 150001,
      "maxBudget": 200000,
      "build": {
        "Processor": "Intel i9-12900K",
        "GPU": "NVIDIA RTX 3080",
        "RAM": "32GB DDR4",
        "SSD": "Samsung 2TB NVMe SSD",
        "HDD": "Seagate Barracuda 4TB HDD",
        "Motherboard": "ASUS ROG Strix Z690-E",
        "PowerSupply": "Corsair RM850x",
        "Case": "NZXT H510 Elite",
      },
    },
  ];

  static const List<Map<String, dynamic>> officeWorkBuilds = [
    {
      "minBudget": 50000,
      "maxBudget": 70000,
      "build": {
        "Processor": "Intel i3-12100",
        "GPU": "Integrated UHD Graphics 730",
        "RAM": "8GB DDR4",
        "SSD": "Crucial 240GB SSD",
        "HDD": "WD Blue 1TB HDD",
        "Motherboard": "Gigabyte B660M DS3H",
        "PowerSupply": "Antec VP450",
        "Case": "Deepcool Matrexx 30",
      },
    },
    {
      "minBudget": 70001,
      "maxBudget": 90000,
      "build": {
        "Processor": "Intel i5-12400",
        "GPU": "Integrated UHD Graphics 750",
        "RAM": "16GB DDR4",
        "SSD": "Samsung 500GB SSD",
        "HDD": "Seagate 1TB HDD",
        "Motherboard": "ASRock B560M Pro4",
        "PowerSupply": "Cooler Master MWE 550W",
        "Case": "NZXT H510",
      },
    },
    {
      "minBudget": 90001,
      "maxBudget": 120000,
      "build": {
        "Processor": "AMD Ryzen 5 3600",
        "GPU": "NVIDIA GTX 1650",
        "RAM": "16GB DDR4",
        "SSD": "Kingston 240GB SSD",
        "HDD": "WD Blue 1TB HDD",
        "Motherboard": "MSI B450 Tomahawk",
        "PowerSupply": "Corsair CX550",
        "Case": "Cooler Master MB511",
      },
    },
    {
      "minBudget": 120001,
      "maxBudget": 150000,
      "build": {
        "Processor": "Intel i5-11400",
        "GPU": "NVIDIA GTX 1660 Super",
        "RAM": "16GB DDR4",
        "SSD": "Samsung 500GB NVMe SSD",
        "HDD": "Seagate 1TB HDD",
        "Motherboard": "MSI B560M Pro-VDH",
        "PowerSupply": "Cooler Master MWE 650W",
        "Case": "NZXT H510",
      },
    },
  ];

  static const List<Map<String, dynamic>> graphicDesigningBuilds = [
    {
      "minBudget": 50000,
      "maxBudget": 70000,
      "build": {
        "Processor": "AMD Ryzen 5 3600",
        "GPU": "NVIDIA GTX 1650",
        "RAM": "16GB DDR4",
        "SSD": "Kingston 240GB SSD",
        "HDD": "WD Blue 1TB HDD",
        "Motherboard": "MSI B450 Tomahawk",
        "PowerSupply": "Corsair CX550",
        "Case": "Cooler Master MB511",
      },
    },
    {
      "minBudget": 70001,
      "maxBudget": 90000,
      "build": {
        "Processor": "Intel i5-11400",
        "GPU": "NVIDIA GTX 1660 Super",
        "RAM": "16GB DDR4",
        "SSD": "Samsung 500GB NVMe SSD",
        "HDD": "Seagate 1TB HDD",
        "Motherboard": "MSI B560M Pro-VDH",
        "PowerSupply": "Cooler Master MWE 650W",
        "Case": "NZXT H510",
      },
    },
    {
      "minBudget": 90001,
      "maxBudget": 120000,
      "build": {
        "Processor": "Intel i7-12700",
        "GPU": "NVIDIA RTX 3060 Ti",
        "RAM": "16GB DDR4",
        "SSD": "Samsung 1TB NVMe SSD",
        "HDD": "Seagate 2TB HDD",
        "Motherboard": "ASRock Z690 Phantom Gaming",
        "PowerSupply": "Corsair RM750",
        "Case": "Fractal Design Meshify C",
      },
    },
    {
      "minBudget": 120001,
      "maxBudget": 150000,
      "build": {
        "Processor": "AMD Ryzen 7 5800X",
        "GPU": "NVIDIA RTX 3070",
        "RAM": "32GB DDR4",
        "SSD": "Corsair 1TB NVMe SSD",
        "HDD": "WD Black 2TB HDD",
        "Motherboard": "MSI MAG X570 TOMAHAWK WIFI",
        "PowerSupply": "EVGA SuperNOVA 750 G5",
        "Case": "Corsair 4000D Airflow",
      },
    },
  ];
}
