// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7VYSPPJTEbLwzSIlkvN4aRQU67JkH9co',
    appId: '1:44335332742:web:d0697624c2aadfcf280007',
    messagingSenderId: '44335332742',
    projectId: 'pcgenius-2bab7',
    authDomain: 'pcgenius-2bab7.firebaseapp.com',
    storageBucket: 'pcgenius-2bab7.firebasestorage.app',
    measurementId: 'G-V19JVYB857',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6WXqfco0MA4LqqqqlHijzYBIv0DGS4Y0',
    appId: '1:44335332742:android:068e27a0a4b583b5280007',
    messagingSenderId: '44335332742',
    projectId: 'pcgenius-2bab7',
    storageBucket: 'pcgenius-2bab7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRkBjrySdBnDCwV_wDiB2_0qxl_1UxN0',
    appId: '1:44335332742:ios:7ff99f1b35b39c6e280007',
    messagingSenderId: '44335332742',
    projectId: 'pcgenius-2bab7',
    storageBucket: 'pcgenius-2bab7.firebasestorage.app',
    iosBundleId: 'com.pcgenius.pcGenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbRkBjrySdBnDCwV_wDiB2_0qxl_1UxN0',
    appId: '1:44335332742:ios:7ff99f1b35b39c6e280007',
    messagingSenderId: '44335332742',
    projectId: 'pcgenius-2bab7',
    storageBucket: 'pcgenius-2bab7.firebasestorage.app',
    iosBundleId: 'com.pcgenius.pcGenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7VYSPPJTEbLwzSIlkvN4aRQU67JkH9co',
    appId: '1:44335332742:web:d647e5e1396af1d1280007',
    messagingSenderId: '44335332742',
    projectId: 'pcgenius-2bab7',
    authDomain: 'pcgenius-2bab7.firebaseapp.com',
    storageBucket: 'pcgenius-2bab7.firebasestorage.app',
    measurementId: 'G-MH8WV84LZ8',
  );
}
